# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: myagentpool
  vmImage: ubuntu-latest
  
  
stages:
  - stage: MavenBuild
    displayName: Build Maven Image
    jobs:
      - job: Buildimageanddockerpush
        displayName: ImageBuild
        pool:
           name:  myagentpool
           vmImage: ubuntu-latest
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'install'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        
        
            



